### ISSUE TITLE
no PIP3 install?

### ISSUE THREAD

**Issue by andygodber** [optiz0r/energy-usage#2]
Hi Ben - thanks for your work on this, but Im having some basic trouble trying to install.

EDIT: In order to progress, I copied the files down to my linux box, maintaining the directory structure.
I ran the PIP3 install with requirements.txt
I then executed the setup.py script; I had to comment out the lines referring to VERSION as this was not defined anywhere, and no import file that was apparent.
This allowed the build to apparently work, but then trying to run the energy-usage module generates errors:

[root@centos8-agnet energyusage]# python3 setup.py install --verbose
running install
running bdist_egg
running egg_info
writing energy_usage.egg-info/PKG-INFO
writing dependency_links to energy_usage.egg-info/dependency_links.txt
writing entry points to energy_usage.egg-info/entry_points.txt
writing top-level names to energy_usage.egg-info/top_level.txt
reading manifest file 'energy_usage.egg-info/SOURCES.txt'
writing manifest file 'energy_usage.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying config.yaml.example -> /etc/energy-usage/config.yaml.example
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying energy_usage.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/energy_usage-0.0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing energy_usage-0.0.0-py3.6.egg
removing '/usr/local/lib/python3.6/site-packages/energy_usage-0.0.0-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/site-packages/energy_usage-0.0.0-py3.6.egg
Extracting energy_usage-0.0.0-py3.6.egg to /usr/local/lib/python3.6/site-packages
energy-usage 0.0.0 is already the active version in easy-install.pth
Installing energy-usage script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/energy_usage-0.0.0-py3.6.egg
Processing dependencies for energy-usage==0.0.0
Finished processing dependencies for energy-usage==0.0.0

[root@centos8-agnet energyusage]# energy-usage
Traceback (most recent call last):
  File "/usr/local/bin/energy-usage", line 11, in <module>
    load_entry_point('energy-usage==0.0.0', 'console_scripts', 'energy-usage')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'energy_usage'

**Comment by optiz0r** [comment]
Looks like I forgot to publish it to pypi, is done now. I was only using this via docker which installed the package locally.

VERSION is defined in `energy_usage/__init__.py`, so provided CWD is on the pythonpath, this should work. It looks like it is by default at least on my distro, `env PYTHONPATH=. ./setup.py ...` should do the trick if not.

Installing into a clean virtualenv from pypi now working for me (with the additional step of installing the dependencies because I have failed to include them in the setup file).

```
$ python -m venv ~/.virtualenvs/test
$ source ~/.virtualenvs/test/bin/activate
$ pip install energy-usage
$ pip install -r requirements.txt
$ energy-usage
energy-usage[15903]: INFO Connected with result code 0
energy-usage[15903]: WARNING Received a payload without expected data
^C
```

I'm not currently using this code because supplier broke my CAD and won't fix it.

**Comment by optiz0r** [comment]
0.4 pushed to pypi which includes the `install_requires`, so this now cleanly installs from `pip install energy-usage`.
