### ISSUE TITLE
Windows docker install

### ISSUE THREAD

**Issue by mbissell** [optiz0r/energy-usage#3]
Hi,

I have been trying to get this running but having some issues, I have desktop docker installed on windows10. 

I have done the docker build successfully and I have copied `config.yaml.example` to `config.yaml` and filled in my MQTT login details.

The folder path is set up as below

C:\Users\Mark\energy-usage

with the config.yaml in this location, however I get the error below error,

C:\Users\Mark>docker run -v config.yaml:/energy-usage/config.yaml energy-usage:latest
Traceback (most recent call last):
  File "/usr/local/bin/energy-usage", line 33, in <module>
    sys.exit(load_entry_point('energy-usage==0.4', 'console_scripts', 'energy-usage')())
  File "/usr/local/lib/python3.10/site-packages/energy_usage-0.4-py3.10.egg/energy_usage/main.py", line 72, in main
    config = load_config(args)
  File "/usr/local/lib/python3.10/site-packages/energy_usage-0.4-py3.10.egg/energy_usage/main.py", line 36, in load_config
    validate_config(config)
  File "/usr/local/lib/python3.10/site-packages/energy_usage-0.4-py3.10.egg/energy_usage/main.py", line 50, in validate_config
    key.get(datatype)
  File "/usr/local/lib/python3.10/site-packages/confuse/core.py", line 351, in get
    return templates.as_template(template).value(self, template)
  File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 64, in value
    return self.get_default_value(view.name)
  File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 69, in get_default_value
    raise exceptions.NotFoundError(u"{} not found".format(key_name))
confuse.exceptions.NotFoundError: mqtt.username not found

I have tried placing the config.yml file in different locations with no luck, 

Please can you help me with the correct location for this file ?

Many thanks

Mark

**Comment by optiz0r** [comment]
Try instead:

```
docker run -e ENERGY-USAGEDIR=/energy-usage/ -v C:\Users\Mark\energy-usage\config.yaml:/energy-usage/config.yaml energy-usage:latest
```

I have not used docker on windows, so don't know exactly how bind-mounting of windows directories into the container will work. I did just test this under wsl2 where it seems to start up OK:

```
[ben@serenity ben]$ podman run -e "ENERGY-USAGEDIR"=/energy-usage/ -v `pwd`/config.yaml:/energy-usage/config.yaml energy
-usage:latest
energy-usage[1]: INFO Connected with result code 0
```

**Comment by mbissell** [comment]
Hi,

thanks for getting back to me, that has worked  :-)

the only other question I have now is that it is giving a warning after its connected.

energy-usage[1]: INFO Connected with result code 0

energy-usage[1]: WARNING Received a payload without expected data

**Comment by optiz0r** [comment]
I think there are periodically different kinds of messages published, some
of which don't contain meter readings. This is just a warning because this
tool only handles messages with readings, and it prints a warning when it
receives one without. Should be safe to ignore.

**Comment by mbissell** [comment]
great, thanks for your help. This program is really helpful,

I'm presuming that this publishes to an already existing influxdb ? I have one currently already running so I have updated the config file with that server and port details. However there are no database , creds like user /pw or db name used in the config.

I have imported the json file into grafana, but this also shows that datasource is looking for a prometheous type

![image](https://user-images.githubusercontent.com/27361874/169165208-256a52d6-67c6-4ed2-822e-f840688d8caf.png)

Can you let me know how you set this up to publish to a influxdb ?

Many thanks

Mark

**Comment by optiz0r** [comment]
I use Victoria metrics, which has an influx like interface for submitting
metrics with no auth enabled, and a prometheus compatible query interface.

**Comment by mbissell** [comment]
Hi, 

I hope you might know the answer to this or be able to suggest what to check next.

I have installed Victoria metrics and confirmed that its up and running.  using the command below which works fine

 curl -v http://localhost:8428/metrics

I have added a new datasource in grafana for prometheus using this address and access set to browser with auth off.

![image](https://user-images.githubusercontent.com/27361874/169380085-2cbc0c10-faf1-4167-8492-e0149b055c5d.png)

I have set the http method to GET. . I have tested the connection and it connects and I have saved it ok.

the config.yml file has the below, however I'm not seeing any data loaded into VictoriaMetrics,

influx:
  server: localhost
  port: 8428

If I run energy-usage using the --debug flag I do see that data is being pulled down successfully.

Can you point me in the right direction ?

thanks

**Comment by optiz0r** [comment]
I'm assuming you're running victoria-metrics natively on the host, and not inside another container, since you mentioned installing it.

Unless you're running the energy-usage container with `--net=host` meaning it shares the host's network namespace, then localhost within the container is not the same as localhost on the host. 

You could either:
- Bind victoria-metrics to 0.0.0.0 (all network interfaces), and target it from inside the energy-usage's container using an IP address assigned to the host instead of localhost/127.0.0.1
- Run the energy-usage container in the host's network namespace, so that localhost within the container does refer to the host itself. (This should be fine, since the energy-usage container doesn't open any listening ports, there's no risk of conflicts)

You could also arrange to run both energy-usage and victoria-metrics as separate containers inside the same network namespace, but that's a bit more complex.

Again, I'm familiar with network namespaces and containers under linux, but not how Docker Desktop on Windows works, and the behaviour might be slightly different there.

**Comment by mbissell** [comment]
thanks for your input, I'm actually running Victoria M via in another docker container, I will try what you have suggested

cheers

**Comment by optiz0r** [comment]
Running them both with `--net=host` would probably help, then.

**Comment by mbissell** [comment]
Hi

I'm still having issues with getting the data out of energy-usage. As a test to rule out the the docker communication issue.

I have installed the energy-usage app via pip on ubuntu wsl and also running the binary of victoria metrics in the same ubuntu wsl machine.  However still when running  both of the apps I can see no data being pushed from the energy app to victoria metrics. I'm presuming this is the case as I can see that no records are appearing in the logs for victoria metrics. If I manually post a insert of data to Victoria metrics I can see lines in the logs that refer to inserts.

If I run the energy-usage with the -noop flag it does not show what data will be published to influx, but if I run with --debug I can see that pulled data.

I really want to get this to work as this is a perfect solution that will allow my parents to view their usage.

Thanks for any help it is appreciated

**Comment by mbissell** [comment]
ok I have spent a couple of hours verifying the vitorica metrics setup and I'm happy that is working correctly,

I can see the queries grafana is performing against it to retrieve the data, however as there is no data being pushed nothing is being retrived from the dashboard.

Please can you tell me what should be in the config file for the influx set up. I have tried localhost. IP of the machine. url address. Nothing I have tried so far is getting the data to push from the script, I must be missing something but unsure what at the min

example below 

influx:
  server: 192.168.1.101
  port: 8428

**Comment by optiz0r** [comment]
This is all I needed to see the http request headers and response from the influxdb client. Running under wsl (fedora) on win11.

vmetrics test against the latest container version (no data persisted, so obviously don't do this for real)

```bash
podman run --rm -ti -p 8428:8428 victoriametrics/victoria-metrics
```

With energy-usage `config.yaml` set to:

```yaml
---
mqtt:
  username: xxx
  password: xxx
  topic: SMART/HILD/xxx

influx:
  server: localhost
  port: 8428
```

With energy-usage from git master (b7b57fb05e46257af96db287ed9eff63cb4c5677) plus the following diff to enable debug on the influx client:

```
diff --git a/energy_usage/main.py b/energy_usage/main.py
index 963b388..ae18f8d 100644
--- a/energy_usage/main.py
+++ b/energy_usage/main.py
@@ -6,6 +6,8 @@ import sys

 import confuse

+from http.client import HTTPConnection
+
 from energy_usage.influx_client import InfluxClient
 from energy_usage.mqtt_client import MqttClient
 from energy_usage.sep import parse_sep, usage_to_datapoints
@@ -55,6 +57,7 @@ def setup_logging(prog, config):

     if config['debug'].get(bool):
         logger.setLevel(logging.DEBUG)
+        HTTPConnection.debuglevel = 1
     else:
         logger.setLevel(logging.INFO)
```

Running it like: 

```bash
env PYTHONPATH=. ENERGY-USAGEDIR=. python3 ./energy_usage/main.py --debug
```

And I see debug like

```
header: X-Influxdb-Version: 1.8.0
header: X-Server-Hostname: 87118abc42c0
header: Date: Mon, 23 May 2022 20:20:37 GMT
energy-usage[280]: DEBUG http://localhost:8428 "POST /write?db=default HTTP/1.1" 204 0
energy-usage[280]: DEBUG SMART/HILD/xxx b'{"elecMtr":{"0702":xxx ,"smetsVer":"SMETS2","ets":"2000-01-01 00:00:00","gid":"xxx"}'
send: b'POST /write?db=default HTTP/1.1\r\nHost: localhost:8428\r\nUser-Agent: python-requests/2.27.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/x-msgpack\r\nConnection: keep-alive\r\nContent-Type: application/octet-stream\r\nContent-Length: 407\r\nAuthorization: Basic xxx\r\n\r\n'
send: b'electricity,gid=xxx,mpan=xxx,topic=SMART/HILD/xxx consumption_daily=xxx,consumption_monthly=Xxx,consumption_weekly=xxx,draw=xxx,meter_reading=xxx 1653337249000000000\ngas,gid=xxx,mpan=xxx,topic=SMART/HILD/xxxconsumption_daily=xxx,consumption_monthly=xxx,consumption_weekly=xxx,meter_reading=xxx 1653337249000000000\n'
reply: 'HTTP/1.1 204 No Content\r\n'
header: X-Influxdb-Version: 1.8.0
header: X-Server-Hostname: 87118abc42c0
header: Date: Mon, 23 May 2022 20:20:49 GMT
energy-usage[280]: DEBUG http://localhost:8428 "POST /write?db=default HTTP/1.1" 204 0
```

Using vmetric's built in UI, I can see data points for `electricity_meter_usage`.

**Comment by mbissell** [comment]
Hi,

Thanks for the latest suggestion. That would have been perfect to see what data was getting posted.

However I have followed what you suggested. This time I have used a rasp pi to run energy-usage / VM

I pulled down the latest branch to the pi, updated the main file with the additions below.  I'm at a loss of what the issue could be now, 

config.yaml
---
mqtt:
  username: xxx
  password: xxx
  topic: SMART/HILD/xxx

influx:
  server: localhost
  port: 8428


main.py
import confuse

from http.client import HTTPConnection

def setup_logging(prog, config):
    logger = logging.getLogger()

    if config['debug'].get(bool):
        logger.setLevel(logging.DEBUG)
        HTTPConnection.debuglevel = 1
    else:
        logger.setLevel(logging.INFO


Vic Merics running on pi, accessible over the lan via browser

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8428            0.0.0.0:*               LISTEN      31070/./victoria-me


On execution the script is still not posting any data

pi@raspberrypi:~/energy-usage $ env PYTHONPATH=. ENERGY-USAGEDIR=. python3 ./energy_usage/main.py --debug
energy-usage[31084]: INFO Connected with result code 0
energy-usage[31084]: DEBUG SMART/HILD/441793504CD4 b'{"elecMtr":{"0702":{"03":{"01":"00000001","04":"00","02":"000003E8","07":"1591060660734","03":"2B","08":"","00":"00","06":"00"},"00":{"07":"00000000","01":"000000000000","00":"00000017BFD2","14":"02","02":"000000000000"},"04":{"01":"004656","40":"0B3269","30":"009782","00":"00000591"},"02":{"00":"00"}},"0705":{"00":{"01":"00000000","00":"0C94"}},"0708":{"01":{"01":"EONNext"}}},"gasMtr":{"0702":{"00":{}}},"ts":"2022-05-24 22:04:01","hversion":"GLOW-IHD-01-1v4-SMETS2","time":"628D5651","zbSoftVer":"1.2.5","gmtime":1653429841,"pan":{"rssi":"B0","status":"joined","nPAN":"00","join":"0","lqi":"50"},"smetsVer":"SMETS2","ets":"2000-01-01 00:00:00","gid":"70B3D521E000E432"}'
energy-usage[31084]: DEBUG Ignoring payload missing metric: gasMtr.0702.03.01
energy-usage[31084]: WARNING Received a payload without expected data


I'm beginning to think that the DEBUG error "DEBUG Ignoring payload missing metric: gasMtr.0702.03.01" is meaning that the payload is being dropped possibly so is not being sent hence why cant see this even with the additional logging?

Is there a way where it can be set for what data is ignored if there is a missing metric?

**Comment by optiz0r** [comment]
Yes, the code demands several fields are present including that one, and if any are missing it drops the message entirely and does not publish the metrics to influx/vmetrics:

https://github.com/optiz0r/energy-usage/blob/master/energy_usage/sep.py#L36

This is not currently configurable. I can try to make it handle the missing gas meter metric, but won't be able to test it for real, and might take a few days to get to it. If you're happy tweaking the code yourself, a PR would be welcomed.

**Comment by mbissell** [comment]
hi yeah, I spotted that late last night and managed to get it to work by removing all the sections referring to the gas meter from the sep.py. 

pi@raspberrypi:~/energy-usage/energy_usage $ diff sep.py sep.py.bk
35a36,37
>         assert(_get_metric(["gasMtr", "0702", "03", "01"]) == 1)  # m3
>         assert(_get_metric(["gasMtr", "0702", "03", "12"]) == 0)  # kWh
48a51,57
>     gas_daily_consumption = _get_metric(["gasMtr", "0702", "0C", "01"])
>     gas_weekly_consumption = _get_metric(["gasMtr", "0702", "0C", "30"])
>     gas_monthly_consumption = _get_metric(["gasMtr", "0702", "0C", "40"])
>     gas_multiplier = _get_metric(["gasMtr", "0702", "03", "01"])
>     gas_divisor = _get_metric(["gasMtr", "0702", "03", "02"])
>     gas_meter = _get_metric(["gasMtr", "0702", "00", "00"])
>     gas_mpan = _get_metric(["gasMtr", "0702", "03", "07"], str)
68a78,88
>         'gas': {
>             'tags': {
>                 'mpan': gas_mpan,
>             },
>             'metrics': {
>                 'consumption_daily': gas_daily_consumption * gas_multiplier / gas_divisor,
>                 'consumption_weekly': gas_weekly_consumption * gas_multiplier / gas_divisor,
>                 'consumption_monthly': gas_monthly_consumption * gas_multiplier / gas_divisor,
>                 'meter_reading': gas_meter * gas_multiplier / gas_divisor,
>             },
>         },
77c97
<     for utility in ['electricity']:
---
>     for utility in ['electricity', 'gas']:

I'm just a newby at python at the moment, so wouldn't be able to update the code to handle both scenarios as yet.

I'm happy to test the code for you once you do get a chance to make it handle both :-)

**Comment by optiz0r** [comment]
Can you test what's in the `single_fuel` branch, which should handle messages with only electricity or gas data in.

I've also tweaked the debug code to print what's being published to influx, whether or not `--noop` is enabled.

If it works for you, I'll merge that branch into master and cut a new release.

**Comment by optiz0r** [comment]
Branch updated, removed that invalid noop parameter.

**Comment by mbissell** [comment]
thats looks to be working ok

pi@raspberrypi:~/single/energy-usage $ env PYTHONPATH=. ENERGY-USAGEDIR=. python3 ./energy_usage/main.py --debug
energy-usage[6833]: INFO Connected with result code 0
energy-usage[6833]: DEBUG SMART/HILD/441793504CD4 b'{"elecMtr":{"0702":{"03":{"01":"00000001","04":"00","02":"000003E8","07":"1591060660734","03":"2B","08":"","00":"00","06":"00"},"00":{"07":"00000000","01":"000000000000","00":"000000180833","14":"02","02":"000000000000"},"04":{"01":"00433B","40":"0B7ACB","30":"00DFE4","00":"00000858"},"02":{"00":"00"}},"0705":{"00":{"01":"00000000","00":"0C94"}},"0708":{"01":{"01":"EONNext"}}},"gasMtr":{"0702":{"00":{}}},"ts":"2022-05-25 20:59:39","hversion":"GLOW-IHD-01-1v4-SMETS2","time":"628E98BB","zbSoftVer":"1.2.5","gmtime":1653512379,"pan":{"rssi":"AE","status":"joined","nPAN":"00","join":"0","lqi":"48"},"smetsVer":"SMETS2","ets":"2000-01-01 00:00:00","gid":"70B3D521E000E432"}'
energy-usage[6833]: DEBUG Ignoring payload missing metric: gasMtr.0702.03.01
energy-usage[6833]: DEBUG Writing metrics to influx: [{'measurement': 'electricity', 'tags': {'topic': 'SMART/HILD/441793504CD4', 'gid': '70B3D521E000E432', 'mpan': '1591060660734'}, 'time': '2022-05-25T20:59:39+00:00', 'fields': {'draw': 2.136, 'consumption_daily': 17.211, 'consumption_weekly': 57.316, 'consumption_monthly': 752.331, 'meter_reading': 1574.963}}]
energy-usage[6833]: DEBUG Starting new HTTP connection (1): localhost:8428
energy-usage[6833]: DEBUG http://localhost:8428 "POST /write?db=default HTTP/1.1" 204 0

**Comment by optiz0r** [comment]
0.5 has now been pushed to pypi

**Comment by optiz0r** [comment]
In my energy usage config, I have only

```yaml
influx:
                  server: victoria-metrics.service.consul.
<http://victoria-metrics.service.consul.sihnon.net>example.com
                  port: 8428
 ```

My vmetrics has no additional cli options to make influx work. I'm running
v1.71 currently, which is a bit old. I'll try upgrading mine to latest and
make sure I'm still receiving metrics.

The code currently doesn't make `--debug` option show what's being
published to influx. If I have time this week, I'll see if I can make that
bit more verbose.
